// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/kyc" | "/audit-report" | "/blog" | "/blog/[slug]" | "/checkout" | "/complaints" | "/compliance" | "/contact" | "/dashboard" | "/dashboard/account" | "/dashboard/portfolio" | "/dashboard/rebalances" | "/dashboard/research" | "/investor-charter" | "/kyc" | "/login" | "/performance" | "/strategies" | "/strategies/[slug]" | "/strategies/[slug]/performance" | "/subscribe/[slug]"
type AppRouteHandlerRoutes = "/api/admin/kyc/rerun" | "/api/admin/kyc/review" | "/api/auth/send-otp" | "/api/checkout/create" | "/api/contact" | "/api/execution/strategies/[strategy_id]/latest-model-portfolio.csv" | "/api/execution/strategies/[strategy_id]/rebalance-history.csv" | "/api/execution/subscriptions" | "/api/info/subscribe" | "/api/kyc/submit" | "/api/performance-access" | "/api/razorpay/webhook" | "/api/rebalance-reviews" | "/api/strategies/[slug]/exports/[kind]" | "/auth/callback" | "/execution/connect"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/kyc": {}
  "/api/admin/kyc/rerun": {}
  "/api/admin/kyc/review": {}
  "/api/auth/send-otp": {}
  "/api/checkout/create": {}
  "/api/contact": {}
  "/api/execution/strategies/[strategy_id]/latest-model-portfolio.csv": { "strategy_id": string; }
  "/api/execution/strategies/[strategy_id]/rebalance-history.csv": { "strategy_id": string; }
  "/api/execution/subscriptions": {}
  "/api/info/subscribe": {}
  "/api/kyc/submit": {}
  "/api/performance-access": {}
  "/api/razorpay/webhook": {}
  "/api/rebalance-reviews": {}
  "/api/strategies/[slug]/exports/[kind]": { "slug": string; "kind": string; }
  "/audit-report": {}
  "/auth/callback": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/checkout": {}
  "/complaints": {}
  "/compliance": {}
  "/contact": {}
  "/dashboard": {}
  "/dashboard/account": {}
  "/dashboard/portfolio": {}
  "/dashboard/rebalances": {}
  "/dashboard/research": {}
  "/execution/connect": {}
  "/investor-charter": {}
  "/kyc": {}
  "/login": {}
  "/performance": {}
  "/strategies": {}
  "/strategies/[slug]": { "slug": string; }
  "/strategies/[slug]/performance": { "slug": string; }
  "/subscribe/[slug]": { "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
