// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/kyc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/kyc">> = Specific
  const handler = {} as typeof import("../../app/admin/kyc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit-report">> = Specific
  const handler = {} as typeof import("../../app/audit-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/complaints/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/complaints">> = Specific
  const handler = {} as typeof import("../../app/complaints/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/compliance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance">> = Specific
  const handler = {} as typeof import("../../app/compliance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/account">> = Specific
  const handler = {} as typeof import("../../app/dashboard/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/portfolio">> = Specific
  const handler = {} as typeof import("../../app/dashboard/portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/rebalances/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/rebalances">> = Specific
  const handler = {} as typeof import("../../app/dashboard/rebalances/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/research/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/research">> = Specific
  const handler = {} as typeof import("../../app/dashboard/research/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/investor-charter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investor-charter">> = Specific
  const handler = {} as typeof import("../../app/investor-charter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/kyc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kyc">> = Specific
  const handler = {} as typeof import("../../app/kyc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance">> = Specific
  const handler = {} as typeof import("../../app/performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/strategies/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/strategies/[slug]">> = Specific
  const handler = {} as typeof import("../../app/strategies/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/strategies/[slug]/performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/strategies/[slug]/performance">> = Specific
  const handler = {} as typeof import("../../app/strategies/[slug]/performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/strategies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/strategies">> = Specific
  const handler = {} as typeof import("../../app/strategies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/subscribe/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscribe/[slug]">> = Specific
  const handler = {} as typeof import("../../app/subscribe/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/kyc/rerun/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/kyc/rerun">> = Specific
  const handler = {} as typeof import("../../app/api/admin/kyc/rerun/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/kyc/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/kyc/review">> = Specific
  const handler = {} as typeof import("../../app/api/admin/kyc/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/send-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/send-otp">> = Specific
  const handler = {} as typeof import("../../app/api/auth/send-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/checkout/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout/create">> = Specific
  const handler = {} as typeof import("../../app/api/checkout/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/execution/strategies/[strategy_id]/latest-model-portfolio.csv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/execution/strategies/[strategy_id]/latest-model-portfolio.csv">> = Specific
  const handler = {} as typeof import("../../app/api/execution/strategies/[strategy_id]/latest-model-portfolio.csv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/execution/strategies/[strategy_id]/rebalance-history.csv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/execution/strategies/[strategy_id]/rebalance-history.csv">> = Specific
  const handler = {} as typeof import("../../app/api/execution/strategies/[strategy_id]/rebalance-history.csv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/execution/subscriptions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/execution/subscriptions">> = Specific
  const handler = {} as typeof import("../../app/api/execution/subscriptions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/info/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/info/subscribe">> = Specific
  const handler = {} as typeof import("../../app/api/info/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/kyc/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kyc/submit">> = Specific
  const handler = {} as typeof import("../../app/api/kyc/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/performance-access/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/performance-access">> = Specific
  const handler = {} as typeof import("../../app/api/performance-access/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/razorpay/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/razorpay/webhook">> = Specific
  const handler = {} as typeof import("../../app/api/razorpay/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rebalance-reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rebalance-reviews">> = Specific
  const handler = {} as typeof import("../../app/api/rebalance-reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/strategies/[slug]/exports/[kind]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/strategies/[slug]/exports/[kind]">> = Specific
  const handler = {} as typeof import("../../app/api/strategies/[slug]/exports/[kind]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/execution/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/execution/connect">> = Specific
  const handler = {} as typeof import("../../app/execution/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
